### ISSUE TITLE
Upgrade npm dependencies

### ISSUE THREAD

**Issue by ipselon** [webcodesk/webcodesk-srv#17]

**Comment by jycouet** [comment]
Do you know about [renovate](https://github.com/renovatebot/renovate)?
Quite easy to setup with [GitHub App Installation](https://docs.renovatebot.com/install-github-app/)

I did a small test on a fork to show you. The Onboarding PR: https://github.com/jycouet/webcodesk-srv/pull/1
- After merging this, it will create other 32 PRs
- Then, over time, it will keep doing PR as soon as some dependencies are updating

**Comment by ipselon** [comment]
I have a very bad experience with upgrading npm modules without checking out their changelog. So now I'm reading changelog before upgrading each module.

**Comment by jycouet** [comment]
Yes, it's a good point and maybe not the right timing.

We could also imagine having some tests so that each PR will get tested.

Actually, after the big update that you plan to do manually, it could be good to setup this so that you are warned when you need to check new changelogs. It's like keeping your aware.

**Comment by ipselon** [comment]
Yeah. Adding unit tests is my technical debt. I'll try to add them once the project gains some traction.
